importScripts('/third_party/workbox/workbox-v7.1.0/workbox-sw.js');

// import {build, files} from '$service-worker';

const precache_list = [
    "/",
    "./color.js-main/color.js",
    "./color.js-main/src/adapt.js",
    "./color.js-main/src/angles.js",
    "./color.js-main/src/CATs.js",
    "./color.js-main/src/chromaticity.js",
    "./color.js-main/src/clone.js",
    "./color.js-main/src/color.d.ts",
    "./color.js-main/src/color.js",
    "./color.js-main/src/ColorSpace.d.ts",
    "./color.js-main/src/ColorSpace.js",
    "./color.js-main/src/contrast/APCA.js",
    "./color.js-main/src/contrast/deltaPhi.js",
    "./color.js-main/src/contrast/index.js",
    "./color.js-main/src/contrast/Lstar.js",
    "./color.js-main/src/contrast/Michelson.js",
    "./color.js-main/src/contrast/WCAG21.js",
    "./color.js-main/src/contrast/Weber.js",
    "./color.js-main/src/contrast.js",
    "./color.js-main/src/defaults.js",
    "./color.js-main/src/deltaE/deltaE2000.js",
    "./color.js-main/src/deltaE/deltaE76.js",
    "./color.js-main/src/deltaE/deltaECMC.js",
    "./color.js-main/src/deltaE/deltaEHCT.js",
    "./color.js-main/src/deltaE/deltaEITP.js",
    "./color.js-main/src/deltaE/deltaEJz.js",
    "./color.js-main/src/deltaE/deltaEOK.js",
    "./color.js-main/src/deltaE/deltaEOK2.js",
    "./color.js-main/src/deltaE/index.js",
    "./color.js-main/src/deltaE.js",
    "./color.js-main/src/deltas.js",
    "./color.js-main/src/display.js",
    "./color.js-main/src/distance.js",
    "./color.js-main/src/equals.js",
    "./color.js-main/src/Format.js",
    "./color.js-main/src/get.js",
    "./color.js-main/src/getAll.js",
    "./color.js-main/src/getColor.js",
    "./color.js-main/src/hooks.d.ts",
    "./color.js-main/src/hooks.js",
    "./color.js-main/src/index-fn.js",
    "./color.js-main/src/index.d.ts",
    "./color.js-main/src/index.js",
    "./color.js-main/src/inGamut.js",
    "./color.js-main/src/interpolation.js",
    "./color.js-main/src/keywords.js",
    "./color.js-main/src/luminance.js",
    "./color.js-main/src/multiply-matrices.js",
    "./color.js-main/src/parse.js",
    "./color.js-main/src/RGBColorSpace.js",
    "./color.js-main/src/serialize.js",
    "./color.js-main/src/set.js",
    "./color.js-main/src/setAll.js",
    "./color.js-main/src/space-accessors.js",
    "./color.js-main/src/space-coord-accessors.d.ts",
    "./color.js-main/src/spaces/a98rgb-linear.js",
    "./color.js-main/src/spaces/a98rgb.js",
    "./color.js-main/src/spaces/acescc.js",
    "./color.js-main/src/spaces/acescg.js",
    "./color.js-main/src/spaces/cam16.js",
    "./color.js-main/src/spaces/hct.js",
    "./color.js-main/src/spaces/hpluv.js",
    "./color.js-main/src/spaces/hsl.js",
    "./color.js-main/src/spaces/hsluv.js",
    "./color.js-main/src/spaces/hsv.js",
    "./color.js-main/src/spaces/hwb.js",
    "./color.js-main/src/spaces/ictcp.js",
    "./color.js-main/src/spaces/index-fn-hdr.js",
    "./color.js-main/src/spaces/index-fn.js",
    "./color.js-main/src/spaces/index.js",
    "./color.js-main/src/spaces/jzazbz.js",
    "./color.js-main/src/spaces/jzczhz.js",
    "./color.js-main/src/spaces/lab-d65.js",
    "./color.js-main/src/spaces/lab.js",
    "./color.js-main/src/spaces/lch.js",
    "./color.js-main/src/spaces/lchuv.js",
    "./color.js-main/src/spaces/luv.js",
    "./color.js-main/src/spaces/okhsl.js",
    "./color.js-main/src/spaces/okhsv.js",
    "./color.js-main/src/spaces/oklab.js",
    "./color.js-main/src/spaces/oklch.js",
    "./color.js-main/src/spaces/oklrab.js",
    "./color.js-main/src/spaces/oklrch.js",
    "./color.js-main/src/spaces/p3-linear.js",
    "./color.js-main/src/spaces/p3.js",
    "./color.js-main/src/spaces/prophoto-linear.js",
    "./color.js-main/src/spaces/prophoto.js",
    "./color.js-main/src/spaces/rec2020-linear.js",
    "./color.js-main/src/spaces/rec2020.js",
    "./color.js-main/src/spaces/rec2100-hlg.js",
    "./color.js-main/src/spaces/rec2100-linear.js",
    "./color.js-main/src/spaces/rec2100-pq.js",
    "./color.js-main/src/spaces/srgb-linear.js",
    "./color.js-main/src/spaces/srgb.js",
    "./color.js-main/src/spaces/xyz-abs-d65.js",
    "./color.js-main/src/spaces/xyz-d50.js",
    "./color.js-main/src/spaces/xyz-d65.js",
    "./color.js-main/src/to.js",
    "./color.js-main/src/toGamut.js",
    "./color.js-main/src/Type.js",
    "./color.js-main/src/types.d.ts",
    "./color.js-main/src/types.js",
    "./color.js-main/src/util.js",
    "./color.js-main/src/variations.js",
    "./fonts/JetBrainsMono-Italic[wght].ttf",
    "./fonts/JetBrainsMono[wght].ttf",
    "./icons/colorPicker.png",
    "./icons/icon.png",
    "./index.html",
    "./manifest.json",
    "./script.js",
    "./service-worker.js",
    "./styles.css"
  ].map((s) => ({
    url: s,
    revision: 1
}));
  
workbox.precaching.precacheAndRoute(precache_list,
    {
        directoryIndex: null,
      }
);



//workbox.setConfig({
//    modulePathPrefix: '/third_party/workbox/workbox-v7.1.0/',
//  });
  
//workbox.routing.registerRoute(
//    () => true,
//    new workbox.strategies.CacheFirst()
//)

// workbox.precaching.precacheAndRoute(self.__WB_MANIFEST || []);